server:
  port: 8090

# Base de dados #

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  base-short-url: "http://localhost:8090/r/"

jwt:
  secret: TXlTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25UaGF0U2hvdWxkQmVMb25nRW5vdWdoRm9yUHJvZHVjdGlvblVzZVdpdGhBdExlYXN0NjRDaGFyYWN0ZXJzMTIzNDU2Nzg5
  expiration: 360000
