server:
  port: 8090

# Base de dados #

spring:
  datasource:
    url: jdbc:postgresql://ep-nameless-cake-ac1aubtl-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_IzyZpmD6H4ak
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

# Migrations #

  flyway:
    enabled: false

